// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travelport.AirportRegistration.Infrastructure;

#nullable disable

namespace Travelport.AirportRegistration.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("Travelport.AirportRegistration.Domain.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MAD",
                            Name = "Adolfo Suárez Madrid–Barajas Airport"
                        },
                        new
                        {
                            Id = 2,
                            Code = "BCN",
                            Name = "Barcelona–El Prat Airport"
                        },
                        new
                        {
                            Id = 3,
                            Code = "AGP",
                            Name = "Málaga Airport"
                        },
                        new
                        {
                            Id = 4,
                            Code = "PMI",
                            Name = "Palma de Mallorca Airport"
                        },
                        new
                        {
                            Id = 5,
                            Code = "ALC",
                            Name = "Alicante–Elche Airport"
                        },
                        new
                        {
                            Id = 6,
                            Code = "LPA",
                            Name = "Gran Canaria Airport"
                        },
                        new
                        {
                            Id = 7,
                            Code = "TFS",
                            Name = "Tenerife South Airport"
                        },
                        new
                        {
                            Id = 8,
                            Code = "VLC",
                            Name = "Valencia Airport"
                        },
                        new
                        {
                            Id = 9,
                            Code = "SVQ",
                            Name = "Seville Airport"
                        },
                        new
                        {
                            Id = 10,
                            Code = "BIO",
                            Name = "Bilbao Airport"
                        },
                        new
                        {
                            Id = 11,
                            Code = "IBZ",
                            Name = "Ibiza Airport"
                        },
                        new
                        {
                            Id = 12,
                            Code = "MAH",
                            Name = "Menorca Airport"
                        },
                        new
                        {
                            Id = 13,
                            Code = "SCQ",
                            Name = "Santiago de Compostela Airport"
                        },
                        new
                        {
                            Id = 14,
                            Code = "OVD",
                            Name = "Asturias Airport"
                        },
                        new
                        {
                            Id = 15,
                            Code = "GRO",
                            Name = "Girona–Costa Brava Airport"
                        });
                });

            modelBuilder.Entity("Travelport.AirportRegistration.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Travelport.AirportRegistration.Domain.Entities.Person", b =>
                {
                    b.HasOne("Travelport.AirportRegistration.Domain.Entities.Airport", "Airport")
                        .WithMany("People")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Travelport.AirportRegistration.Domain.Entities.Airport", b =>
                {
                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
